//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLMusteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLMusteriler()
        {
            this.TBLSatis = new HashSet<TBLSatis>();
        }
    
        public int MusterID { get; set; }
        [Required (ErrorMessage ="Ad alaný boþ býrakýlamaz")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakter olacak...!")]
        public string MusterAd { get; set; }
        [Required(ErrorMessage = "Soyad alaný boþ býrakýlamaz")]
        [StringLength(50, ErrorMessage = "En fazla 50 karakter olacak...!")]
        public string MusteriSoyad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSatis> TBLSatis { get; set; }
    }
}
