//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectStok.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUrunler
    {
        public int UrunID { get; set; } 
        public string UrunAdi { get; set; } 
        public Nullable<short> UrunKategori { get; set; } 
        public Nullable<decimal> Fiyat { get; set; } 
        public string Marka { get; set; } 
        public Nullable<byte> Stok { get; set; }
    
        public virtual TBLKategoriler TBLKategoriler { get; set; }
        public virtual TBLSatis TBLSatis { get; set; }
    }
}
